### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by jialesmu** [huchenxucs/ChatDB#8]
Is there any one facing this problem?
When I run chatdb.py it's shows :

```
C:\Users\anaconda3\envs\LLM\python.exe C:/User/Desktop/LLM/ChatDB/chatdb.py
Traceback (most recent call last):
  File "C:/Users/Desktop/LLM/ChatDB/chatdb.py", line 7, in <module>
    from call_ai_function import populate_sql_statement
  File "C:\Users\Desktop\LLM\ChatDB\call_ai_function.py", line 36, in <module>
    def populate_sql_statement(sql_str: str, previous_sql_results: list[list[dict]]) -> list[str]:
TypeError: 'type' object is not subscriptable
```

![image](https://github.com/huchenxucs/ChatDB/assets/40394061/ab1a4d32-d4fb-4f04-8bee-8f0e39201fbf)

and if I change this def function to:
```
from typing import List
def populate_sql_statement(sql_str: str, previous_sql_results: List[List[dict]]) -> List[str]:
```
The result will be like this:
![image](https://github.com/huchenxucs/ChatDB/assets/40394061/5a8ab639-4671-45f1-8f71-2a2850f15247)

Thanks

**Comment by jialesmu** [comment]
Fixed,thanks
